# Generated by Django 4.1.7 on 2023-02-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRaansomware', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
